import { SlideData } from '@/types';

const ACCENT_COLORS: string[] = [
  'cyan-600',
  'blue-600',
  'sky-600',
  'amber-500',
  'orange-500',
  'purple-600',
  'red-700',
  'green-600',
  'gray-600',
  'teal-500',
  'lime-500',
  'indigo-500',
  'pink-600',
  'rose-600',
  'emerald-600',
];

export const SLIDES_DATA: SlideData[] = [
  {
    id: 'slide-1-poluicao-sonora-global-v5',
    slideNumberText: 'Slide 1 de 15',
    title: 'Poluição Sonora: O Problema Invisível e Global',
    mainParagraph: 'Explore os efeitos da segunda causa de poluição mais prejudicial ao planeta, segundo a OMS, superando a poluição da água e ficando atrás apenas da poluição do ar.',
    points: [],
    accentColor: ACCENT_COLORS[0],
  },
  {
    id: 'slide-2-o-que-e-poluicao-sonora-v5',
    slideNumberText: 'Slide 2 de 15',
    title: 'O que é Poluição Sonora?',
    mainParagraph: 'Poluição sonora é a exposição frequente a níveis elevados de ruído indesejado, capaz de causar perda auditiva, distúrbios do sono, doenças cardiovasculares e distúrbios mentais.',
    points: [
      'Cerca de 10% da população mundial está exposta a ruídos prejudiciais.',
      'No Brasil, 6,8% já apresenta perda auditiva relacionada ao ruído.',
      'A OMS considera ruídos acima de 50 dB prejudiciais à saúde; acima de 55 dB já podem causar estresse e outros efeitos negativos.',
    ],
    image: `image/image-2.png`,
    accentColor: ACCENT_COLORS[1],
  },
  {
    id: 'slide-3-principais-fontes-ruido-v5',
    slideNumberText: 'Slide 3 de 15',
    title: 'Principais Fontes de Ruído',
    mainParagraph: 'O tráfego de veículos é a principal fonte de incômodo nas cidades, seguido por vizinhos, sirenes, animais e obras.',
    points: [
      'Tráfego de veículos: incômodo para 67% dos moradores de grandes cidades',
      'Vizinhos: 33%',
      'Sirenes: 23%',
      'Animais: 21%',
      'Construção civil: 21%',
      'O tráfego rodoviário responde por 80% do ruído urbano em áreas metropolitanas.',
    ],
    image: `image/image-3.png`,
    accentColor: ACCENT_COLORS[2],
  },
  {
    id: 'slide-4-niveis-ruido-v5',
    slideNumberText: 'Slide 4 de 15',
    title: 'Níveis de Ruído',
    mainParagraph: 'Áreas residenciais e industriais frequentemente excedem os limites recomendados, expondo a população a riscos à saúde.',
    points: [
      'Zonas residenciais: média de 75,6 dB (limite OMS: 65 dB)',
      'Áreas industriais: até 78,1 dB',
      'Ruídos acima de 70 dB causam desgaste ao organismo em mais de 50% dos expostos.',
    ],
    image: `image/image-4.png`,
    accentColor: ACCENT_COLORS[3],
  },
  {
    id: 'slide-5-impactos-saude-v5',
    slideNumberText: 'Slide 5 de 15',
    title: 'Impactos na Saúde',
    mainParagraph: 'A exposição contínua ao ruído ambiental afeta diretamente a saúde, gerando irritabilidade, insônia e aumentando o risco de doenças graves, como AVC e problemas cardiovasculares.',
    points: [
      '74% dos moradores urbanos sentem-se incomodados pelo ruído',
      'Irritabilidade: 55%',
      'Baixa concentração: 28%',
      'Insônia: 20%',
      'Dor de cabeça: 19%',
      'Ruídos acima de 65 dB aumentam em 7% o risco de AVC em áreas próximas a aeroportos',
      'Mais de 1 bilhão de jovens (12 a 35 anos) estão em risco de perda auditiva por exposição crônica ao ruído.',
    ],
    image: `image/image-5.png`,
    accentColor: ACCENT_COLORS[4],
  },
  {
    id: 'slide-6-consequencias-sociais-v5',
    slideNumberText: 'Slide 6 de 15',
    title: 'Consequências Sociais',
    mainParagraph: 'O excesso de ruído urbano prejudica o convívio, o sono, a concentração e o bem-estar emocional.',
    points: [
      '81,1% relatam incômodo ou irritação',
      '68,5% relatam baixa concentração',
      '42,2% têm alterações no sono',
      '51,4% sofrem dor de cabeça relacionada ao ruído',
      '73,4% associam o ruído ao estresse emocional',
      '87% dos brasileiros acreditam que a poluição sonora prejudica muito a qualidade ambiental',
    ],
    image: `image/image-6.png`,
    accentColor: ACCENT_COLORS[5],
  },
  {
    id: 'slide-7-mortes-cidades-v5',
    slideNumberText: 'Slide 7 de 15',
    title: 'Porcentagem de Mortes e Impacto em Grandes Cidades',
    mainParagraph: 'A poluição sonora está associada a milhares de mortes anuais em grandes centros urbanos, principalmente por agravar doenças cardiovasculares.',
    points: [
      'Estima-se que 0,032% das mortes anuais em grandes cidades estejam ligadas à poluição sonora.',
      'São Paulo: cerca de 11.372 mortes/ano relacionadas à poluição ambiental, sendo o ruído um dos principais fatores.',
      'Tóquio: estimativa proporcional aponta aproximadamente 13.270 mortes/ano atribuíveis à poluição sonora, considerando população e padrões similares a São Paulo.',
      '“A exposição crônica ao ruído pode ser responsável por até 3% das mortes por doenças cardíacas em áreas urbanas.” (OMS).',
    ],
    image: `image/image-7.png`,
    accentColor: ACCENT_COLORS[6],
  },
  {
    id: 'slide-8-efeitos-ambientais-animais-v5',
    slideNumberText: 'Slide 8 de 15',
    title: 'Efeitos Ambientais e nos Animais',
    mainParagraph: 'A poluição sonora afeta o meio ambiente e a fauna urbana e silvestre.',
    points: [
      'Ruídos intensos prejudicam comunicação, reprodução e migração de aves, mamíferos e insetos.',
      'Animais expostos a ruído mostram aumento de estresse, fuga e redução na alimentação.',
      'Espécies sensíveis abandonam habitats urbanos e naturais, reduzindo a biodiversidade.',
      'Exemplo: aves urbanas cantam mais alto ou em horários diferentes para competir com o barulho.',
      'Ruídos urbanos e industriais afetam até áreas protegidas, alterando padrões de sono e alimentação de animais silvestres.',
    ],
    image: `image/image-8.png`,
    accentColor: ACCENT_COLORS[7],
  },
  {
    id: 'slide-9-legislacao-fiscalizacao-v5',
    slideNumberText: 'Slide 9 de 15',
    title: 'Legislação e Fiscalização',
    mainParagraph: 'Apesar de leis e multas, a fiscalização da poluição sonora ainda é insuficiente.',
    points: [
      'Em algumas cidades, 80% das denúncias ambientais são sobre poluição sonora.',
      'Apenas 3,6% das denúncias resultam em autuação efetiva.',
      'Multas podem chegar a R$ 24 mil em São Paulo, mas a reincidência é comum.',
      '86% da população apoia a criminalização da poluição sonora.',
    ],
    image: `image/image-9.png`,
    accentColor: ACCENT_COLORS[8],
  },
  {
    id: 'slide-10-solucoes-boas-praticas-v5',
    slideNumberText: 'Slide 10 de 15',
    title: 'Soluções e Boas Práticas',
    mainParagraph: 'Medidas como zonas de silêncio, barreiras acústicas e campanhas educativas reduzem a exposição ao ruído e melhoram a qualidade de vida.',
    points: [
      'Zonas de silêncio e barreiras acústicas: redução de até 30% no número de pessoas expostas.',
      'Ações educativas aumentam o respeito aos limites de ruído em até 40% dos casos.',
      'Tecnologias de monitoramento e controle acústico reduzem focos de poluição sonora em mais de 60% dos pontos críticos.',
    ],
    image: `image/image-10.png`,
    accentColor: ACCENT_COLORS[9],
  },
  {
    id: 'slide-11-som-desejavel-v5',
    slideNumberText: 'Slide 11 de 15',
    title: 'Som Desejável: Benefícios e Impactos Positivos',
    mainParagraph: 'Promover sons agradáveis, como sons da natureza, música suave ou ruído branco, traz benefícios comprovados para a saúde mental, o convívio social e o ambiente urbano.',
    points: [
      'Redução do estresse em até 60%.',
      'Melhora da qualidade do sono em 35%.',
      'Aumento da concentração em até 50%.',
      'Ambientes com sons agradáveis têm até 10% menos casos de irritabilidade e ansiedade.',
      'Paisagens sonoras positivas podem reduzir o impacto negativo do ruído urbano na saúde e mortalidade em até 15%.',
      'Exemplo: parques urbanos com fontes d’água e áreas verdes promovem relaxamento e melhor convivência.',
    ],
    image: `image/image-11.png`,
    accentColor: ACCENT_COLORS[10],
  },
  {
    id: 'slide-12-inovacoes-tecnologicas-v5',
    slideNumberText: 'Slide 12 de 15',
    title: 'Inovações Tecnológicas no Combate à Poluição Sonora',
    mainParagraph: 'Novas tecnologias estão revolucionando o monitoramento e o controle do ruído urbano.',
    points: [
      'Sensores inteligentes mapeiam pontos críticos em tempo real.',
      'Barreiras acústicas transparentes e ecológicas integram proteção e paisagismo.',
      'Aplicativos permitem que cidadãos denunciem poluição sonora e acompanhem resultados.',
      'Materiais de construção com isolamento acústico avançado reduzem o ruído em edifícios.',
      'Veículos elétricos e infraestrutura urbana silenciosa ajudam a diminuir o ruído nas cidades.',
    ],
    image: `image/image-12.png`,
    accentColor: ACCENT_COLORS[11],
  },
  {
    id: 'slide-13-formas-som-desejavel-v5',
    slideNumberText: 'Slide 13 de 15',
    title: 'Formas de Som Desejável',
    mainParagraph: 'Nem todo som é prejudicial. Sons desejáveis podem transformar ambientes e promover saúde e bem-estar.',
    points: [
      'Sons da natureza: água corrente, canto de pássaros, vento nas árvores e chuva reduzem o estresse.',
      'Ruído branco: sons contínuos e suaves, como ventiladores, ajudam a mascarar ruídos indesejados e melhoram o sono.',
      'Música suave: trilhas instrumentais ou sons ambientes contribuem para relaxamento e foco.',
      'Paisagens sonoras urbanas: fontes d’água e jardins sonoros promovem conforto acústico.',
      'Ambientes personalizados: aplicativos e dispositivos permitem criar trilhas sonoras adaptadas ao gosto de cada pessoa.',
    ],
    image: `image/image-13.jpg`,
    accentColor: ACCENT_COLORS[12],
  },
  {
    id: 'slide-14-conclusao-final-v5',
    slideNumberText: 'Slide 14 de 15',
    title: 'Conclusão',
    mainParagraph: 'Reduzir a poluição sonora é essencial para a saúde e o bem-estar coletivo. Pequenas atitudes e respeito à legislação podem transformar a convivência nas cidades.',
    points: [
      'Poluição sonora afeta diretamente mais de 30% da população urbana mundial.',
      'Reduzir o ruído melhora a qualidade de vida e a saúde coletiva.',
      'Pequenas atitudes beneficiam toda a sociedade.',
    ],
    image: `image/image-14.png`,
    accentColor: ACCENT_COLORS[13],
  },
  {
    id: 'slide-15-mensagem-final-v5',
    slideNumberText: 'Slide 15 de 15',
    title: 'Mensagem Final',
    mainParagraph: 'A poluição sonora é um problema grave, mas evitável. Cada pessoa pode contribuir para cidades mais silenciosas e saudáveis, adotando pequenas atitudes no dia a dia.',
    points: [
      'Pequenas atitudes melhoram saúde, ambiente e convivência.',
    ],
    image: `image/image-15.png`,
    accentColor: ACCENT_COLORS[14],
  },
];
